In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
data_1d=np.array([1,2,3,4])

In [4]:
data_2d=np.array([[1,2,3],[4,5,6]])

In [5]:
print(data_1d.shape)

(4,)


In [6]:
print(data_2d.shape)

(2, 3)


In [7]:
reshape_Arr=data_2d.reshape(3,2)
reshape_Arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
print(data_2d.ndim)

2


In [9]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [10]:
addition=a+b
addition

array([5, 7, 9])

In [11]:
multiplication=a*b
multiplication


array([ 4, 10, 18])

In [12]:
exp_a=np.exp(a)
exp_a

array([ 2.71828183,  7.3890561 , 20.08553692])

In [13]:
log_b=np.log(b)
log_b

array([1.38629436, 1.60943791, 1.79175947])

In [14]:
print(data_1d[:3])

[1 2 3]


In [15]:
data_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
print(data_2d[:,1:])

[[2 3]
 [5 6]]
